/// robots.txt — generated by Next at /robots.txt
///
/// The site had none, so crawlers had no sitemap reference and no guidance on
/// the authenticated/parameterised routes.

import type { MetadataRoute } from 'next';

const SITE_URL = process.env.NEXT_PUBLIC_FAX_SITE_URL || 'https://nftfax.app';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        // /api returns JSON and /tray/* are per-transmission permalinks that
        // decay — neither belongs in an index, and crawling them wastes budget
        // that should go on the public pages.
        disallow: ['/api/'],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
