/// robots.txt — generated by Next at /robots.txt
///
/// The site had none, so crawlers had no sitemap reference and no guidance on
/// the authenticated/parameterised routes.

import type { MetadataRoute } from 'next';

// Default is fax.nftmail.box, NOT nftfax.app: the latter is registrar
// domain-forwarding that 301s to it and DROPS THE PATH, so an absolute
// nftfax.app/og/... URL resolves to the homepage HTML and social previews
// break. Point this at nftfax.app only once that domain serves the app
// directly.
const SITE_URL = process.env.NEXT_PUBLIC_FAX_SITE_URL || 'https://fax.nftmail.box';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        // /api returns JSON and /tray/* are per-transmission permalinks that
        // decay — neither belongs in an index, and crawling them wastes budget
        // that should go on the public pages.
        disallow: ['/api/'],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
