/// sitemap.xml — generated by Next at /sitemap.xml
///
/// Only stable, publicly meaningful routes. Individual /tray/[id] pages are
/// intentionally excluded: they are per-transmission permalinks, they decay
/// after eight days, and listing thousands of short-lived URLs would dilute
/// crawl budget away from the pages that should rank.

import type { MetadataRoute } from 'next';

// Default is fax.nftmail.box, NOT nftfax.app: the latter is registrar
// domain-forwarding that 301s to it and DROPS THE PATH, so an absolute
// nftfax.app/og/... URL resolves to the homepage HTML and social previews
// break. Point this at nftfax.app only once that domain serves the app
// directly.
const SITE_URL = process.env.NEXT_PUBLIC_FAX_SITE_URL || 'https://fax.nftmail.box';

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();
  const routes: { path: string; priority: number; changeFrequency: 'daily' | 'weekly' | 'monthly' }[] = [
    { path: '', priority: 1.0, changeFrequency: 'daily' },
    { path: '/rolofax', priority: 0.9, changeFrequency: 'daily' },
    { path: '/leaderboard', priority: 0.8, changeFrequency: 'daily' },
    { path: '/draw', priority: 0.7, changeFrequency: 'daily' },
    { path: '/about', priority: 0.7, changeFrequency: 'monthly' },
    { path: '/verify', priority: 0.5, changeFrequency: 'monthly' },
  ];

  return routes.map(({ path, priority, changeFrequency }) => ({
    url: `${SITE_URL}${path}`,
    lastModified: now,
    changeFrequency,
    priority,
  }));
}
